// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分頁查詢稽核日誌。支援全文搜尋與日期範圍（YYYY-MM-DD）。` + "`" + `read` + "`" + ` scope Token 可用。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Audit"
                ],
                "summary": "查詢稽核日誌",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "頁碼（預設 1）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "每頁筆數（預設 30，上限 100）",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "全文搜尋關鍵字",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起始日期 YYYY-MM-DD",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "結束日期 YYYY-MM-DD",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/audit.QueryResult"
                        }
                    },
                    "400": {
                        "description": "日期格式錯誤",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "查詢失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/audit/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "依條件匯出稽核日誌為 CSV 檔案（Content-Disposition attachment）。` + "`" + `read` + "`" + ` scope Token 可用。",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Audit"
                ],
                "summary": "匯出稽核日誌（CSV）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "必須為 csv",
                        "name": "format",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "全文搜尋關鍵字",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "起始日期 YYYY-MM-DD",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "結束日期 YYYY-MM-DD",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CSV 檔案內容",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "format 非 csv 或日期格式錯誤",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "以帳號密碼登入（form-urlencoded）。成功後設定 ` + "`" + `session` + "`" + ` cookie；亦有 rate limit（每 IP 每分鐘 5 次嘗試）。",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "登入",
                "parameters": [
                    {
                        "type": "string",
                        "description": "使用者名稱",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密碼",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{username, message}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "缺少帳號或密碼",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "帳號或密碼錯誤",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "description": "登出並清除 session cookie。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "登出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/notify/channels": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "列出所有通知 Channel（Telegram token 遮罩顯示）。` + "`" + `read` + "`" + ` scope Token 可用。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "列出通知 Channels",
                "responses": {
                    "200": {
                        "description": "{\\\"data\\\": [Channel...]}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "notify 未設定",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "建立新的通知 Channel（Slack/Discord/Telegram/Custom webhook）。需 ` + "`" + `full` + "`" + ` scope Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "建立通知 Channel",
                "parameters": [
                    {
                        "description": "Channel 設定",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ChannelPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\\\"data\\\": Channel}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "驗證失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "409": {
                        "description": "已達 Channel 上限（20）",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "建立失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/notify/channels/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "覆寫更新 Channel 設定。Telegram token 留空或以 ` + "`" + `****` + "`" + ` 開頭時保留原值。需 ` + "`" + `full` + "`" + ` scope Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "更新通知 Channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel ID（UUID）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "新的 Channel 設定",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.ChannelPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"data\\\": Channel}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "驗證失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "404": {
                        "description": "Channel 不存在",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "更新失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "刪除 Channel（歷史發送紀錄保留）。需 ` + "`" + `full` + "`" + ` scope Token。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "刪除通知 Channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel ID（UUID）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "404": {
                        "description": "Channel 不存在",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "刪除失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "切換 Channel 的 enabled 狀態。需 ` + "`" + `full` + "`" + ` scope Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "啟用/停用通知 Channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel ID（UUID）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "{\\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.PatchEnabledPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"data\\\": Channel}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "請求無效",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "404": {
                        "description": "Channel 不存在",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "更新失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/notify/channels/{id}/test": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "向指定 Channel 發送測試通知（不寫入 history）。需 ` + "`" + `full` + "`" + ` scope Token。\\n\\n**注意**：發送失敗回 **502 Bad Gateway**（非 500）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "測試通知 Channel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Channel ID（UUID）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.TestResponse"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "404": {
                        "description": "Channel 不存在",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "502": {
                        "description": "發送失敗（success=false, error=原因）",
                        "schema": {
                            "$ref": "#/definitions/handler.TestResponse"
                        }
                    }
                }
            }
        },
        "/notify/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "分頁查詢通知發送紀錄，可依 Channel 與結果篩選。` + "`" + `read` + "`" + ` scope Token 可用。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Notifications"
                ],
                "summary": "查詢通知發送紀錄",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "頁碼（預設 1）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 30,
                        "description": "每頁筆數（預設 30，上限 100）",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "依 Channel ID 篩選",
                        "name": "channel_id",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "all",
                            "success",
                            "failure"
                        ],
                        "type": "string",
                        "description": "all|success|failure（預設 all）",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/notify.HistoryResult"
                        }
                    },
                    "400": {
                        "description": "參數無效",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "查詢失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/services": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "取得所有 systemd 服務列表（名稱、Active/Sub 狀態、開機狀態、鎖定標記等）。` + "`" + `read` + "`" + ` scope Token 可用。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "取得服務列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handler.serviceJSON"
                            }
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "取得服務列表失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/services/batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "對多個服務執行 start/stop/restart（最多 50 個）。鎖定服務會被拒絕。部分失敗仍回 200，以 per-service result 表示。需 ` + "`" + `full` + "`" + ` scope Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "批次操作服務",
                "parameters": [
                    {
                        "description": "批次操作請求",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.batchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.batchResponse"
                        }
                    },
                    "400": {
                        "description": "請求無效（含鎖定服務）",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "取得服務列表失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/services/{name}/config": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "讀取指定服務的 systemd unit 設定檔內容（含 SHA-256 checksum 供後續 PUT baseChecksum）。鎖定服務亦可唯讀檢視。` + "`" + `read` + "`" + ` scope Token 可用。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Config"
                ],
                "summary": "取得服務設定檔",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服務名稱（systemd unit name）",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ServiceConfigResponse"
                        }
                    },
                    "400": {
                        "description": "服務名稱無效",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "404": {
                        "description": "設定檔路徑或檔案不存在",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "413": {
                        "description": "設定檔過大",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "讀取失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "覆寫指定服務的設定檔並執行 daemon-reload。需帶 GET 取得的 ` + "`" + `baseChecksum` + "`" + ` 做並發衝突偵測；衝突時回 409 與 ` + "`" + `currentChecksum` + "`" + `。需 ` + "`" + `full` + "`" + ` scope Token。\\n\\n**半成功**：設定檔已寫入但 daemon-reload 失敗時回 500，附 ` + "`" + `backupPath` + "`" + ` 供手動還原。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Config"
                ],
                "summary": "儲存服務設定檔",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服務名稱（systemd unit name）",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "新設定檔內容與 baseChecksum",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.SaveConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.SaveConfigResponse"
                        }
                    },
                    "400": {
                        "description": "請求無效或缺 base_checksum",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 或路徑不可寫",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "404": {
                        "description": "設定檔路徑不存在",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "409": {
                        "description": "並發衝突（含 currentChecksum）",
                        "schema": {
                            "$ref": "#/definitions/handler.conflictResponse"
                        }
                    },
                    "413": {
                        "description": "設定檔超過 500KB",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "寫入/daemon-reload 失敗（含 backupPath）",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/services/{name}/config/validate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "以 ` + "`" + `systemd-analyze verify` + "`" + ` 驗證設定內容（不寫入）。systemd-analyze 不存在時回 200 ` + "`" + `{valid:false, available:false}` + "`" + `。` + "`" + `read` + "`" + ` scope Token 可用。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service Config"
                ],
                "summary": "驗證服務設定檔",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服務名稱（systemd unit name）",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "{\\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/systemd.ValidateResult"
                        }
                    },
                    "400": {
                        "description": "服務名稱無效或請求無效",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "無法建立暫存檔",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/services/{name}/disable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "停用指定服務（取消開機自動啟動，systemctl disable）。需 ` + "`" + `full` + "`" + ` scope Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "停用服務",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服務名稱（systemd unit name）",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "停用失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/services/{name}/enable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "啟用指定服務（開機自動啟動，systemctl enable）。需 ` + "`" + `full` + "`" + ` scope Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "啟用服務",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服務名稱（systemd unit name）",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "啟用失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/services/{name}/logs/ws": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "升級為 WebSocket 並串流指定服務的 journalctl 即時日誌（每行一個 TextMessage）。\\n\\n**認證**：支援自訂 header 的 ws 客戶端請帶 ` + "`" + `Authorization: Bearer` + "`" + ` header；瀏覽器原生 WebSocket 需 session cookie。\\n**錯誤**：連線後若啟動 journalctl 失敗，會收到 ` + "`" + `{\"error\":\"...\"}` + "`" + ` TextMessage。\\n\\nclient 斷線即取消 journalctl 程序。",
                "tags": [
                    "Logs"
                ],
                "summary": "即時日誌串流（WebSocket）",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服務名稱（systemd unit name）",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "起始行數（預設 100，上限 1000）",
                        "name": "lines",
                        "in": "query"
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols（之後每行一個 JSON TextMessage）"
                    },
                    "400": {
                        "description": "lines 超出範圍或服務名稱無效",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "journalctl 不可用",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/services/{name}/restart": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "重啟指定 systemd 服務。需 ` + "`" + `full` + "`" + ` scope Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "重啟服務",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服務名稱（systemd unit name）",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "重啟失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/services/{name}/start": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "啟動指定 systemd 服務。需 ` + "`" + `full` + "`" + ` scope Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "啟動服務",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服務名稱（systemd unit name）",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{message: \\\"\u003cname\u003e started\\\"}",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "啟動失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/services/{name}/stop": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "停止指定 systemd 服務。需 ` + "`" + `full` + "`" + ` scope Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "停止服務",
                "parameters": [
                    {
                        "type": "string",
                        "description": "服務名稱（systemd unit name）",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "403": {
                        "description": "唯讀 Token 權限不足",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "500": {
                        "description": "停止失敗",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/session": {
            "get": {
                "description": "檢查目前 session 是否已登入（不需驗證）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "檢查 session 狀態",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.sessionJSON"
                        }
                    }
                }
            }
        },
        "/tokens": {
            "get": {
                "description": "列出所有 API Token（遮罩值、狀態、scope）。**僅限 session 登入**（Token 不可管理 Token）。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "summary": "列出 API Tokens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.tokenListResponse"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            },
            "post": {
                "description": "建立 API Token，原始值**僅在此回應揭露一次**（不儲存）。**僅限 session 登入**。名稱不區分大小寫唯一，最多 20 個 active Token。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "summary": "建立 API Token",
                "parameters": [
                    {
                        "description": "建立請求（expires_in_days: -1=永不過期, 1-365=N 天, 0=自訂日期需帶 custom_expiry）",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/token.CreateTokenInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "含原始 token（一次性）",
                        "schema": {
                            "$ref": "#/definitions/token.CreateTokenResponse"
                        }
                    },
                    "400": {
                        "description": "驗證失敗或達上限",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "409": {
                        "description": "名稱重複",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/tokens/{id}/revoke": {
            "post": {
                "description": "撤銷指定 API Token（冪等 — 已撤銷回傳 200 ` + "`" + `already_revoked` + "`" + `）。撤銷後使用該 Token 的請求立即回 401。**僅限 session 登入**。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tokens"
                ],
                "summary": "撤銷 API Token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token ID（UUID）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/token.RevokeResponse"
                        }
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    },
                    "404": {
                        "description": "Token 不存在",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        },
        "/ws": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "升級為 WebSocket 並即時推送服務狀態變更。**連線後不須傳入任何訊息** — 伺服器於狀態變更時主動推送快照（JSON：` + "`" + `{name, active, sub, unitFileState}` + "`" + `），連線建立時亦推送完整快照。\\n\\n**認證**：支援自訂 header 的 ws 客戶端請帶 ` + "`" + `Authorization: Bearer` + "`" + ` header；瀏覽器原生 WebSocket 需 session cookie。\\n**限制**：每個 user 最多 5 個連線，超過回 close 1008（policy violation）。",
                "tags": [
                    "WebSocket"
                ],
                "summary": "服務狀態即時推送（WebSocket）",
                "responses": {
                    "101": {
                        "description": "Switching Protocols（之後為服務狀態快照 JSON TextMessage）"
                    },
                    "401": {
                        "description": "未驗證",
                        "schema": {
                            "$ref": "#/definitions/handler.messageJSON"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audit.Action": {
            "type": "string",
            "enum": [
                "login",
                "logout",
                "start",
                "stop",
                "restart",
                "enable",
                "disable",
                "token_create",
                "token_revoke",
                "config_view",
                "config_save",
                "notify_create",
                "notify_update",
                "notify_delete",
                "notify_toggle",
                "notify_test"
            ],
            "x-enum-comments": {
                "ActionConfigSave": "PUT config 成功（含 reload 失敗已寫入之半成功）",
                "ActionConfigView": "GET config 成功時（含鎖定服務唯讀檢視）"
            },
            "x-enum-descriptions": [
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "GET config 成功時（含鎖定服務唯讀檢視）",
                "PUT config 成功（含 reload 失敗已寫入之半成功）",
                "",
                "",
                "",
                "",
                ""
            ],
            "x-enum-varnames": [
                "ActionLogin",
                "ActionLogout",
                "ActionStart",
                "ActionStop",
                "ActionRestart",
                "ActionEnable",
                "ActionDisable",
                "ActionTokenCreate",
                "ActionTokenRevoke",
                "ActionConfigView",
                "ActionConfigSave",
                "ActionNotifyCreate",
                "ActionNotifyUpdate",
                "ActionNotifyDelete",
                "ActionNotifyToggle",
                "ActionNotifyTest"
            ]
        },
        "audit.Entry": {
            "type": "object",
            "properties": {
                "action": {
                    "$ref": "#/definitions/audit.Action"
                },
                "detail": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/audit.Result"
                },
                "source_ip": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "audit.QueryResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/audit.Entry"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "audit.Result": {
            "type": "string",
            "enum": [
                "success",
                "failure"
            ],
            "x-enum-varnames": [
                "ResultSuccess",
                "ResultFailure"
            ]
        },
        "handler.ChannelPayload": {
            "type": "object",
            "properties": {
                "all_services": {
                    "type": "boolean"
                },
                "chat_id": {
                    "type": "string"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "method": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sub_chat_id": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/notify.ChannelType"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "handler.PatchEnabledPayload": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "handler.SaveConfigRequest": {
            "type": "object",
            "properties": {
                "baseChecksum": {
                    "description": "GET 回傳的 checksum，必填（檔案存在時）",
                    "type": "string"
                },
                "config": {
                    "type": "string"
                }
            }
        },
        "handler.SaveConfigResponse": {
            "type": "object",
            "properties": {
                "backupPath": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.ServiceConfigResponse": {
            "type": "object",
            "properties": {
                "checksum": {
                    "description": "SHA-256 hex，供 PUT baseChecksum",
                    "type": "string"
                },
                "config": {
                    "type": "string"
                },
                "fragmentPath": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                }
            }
        },
        "handler.TestResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handler.batchRequest": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.batchResponse": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.batchResult"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/handler.batchSummary"
                }
            }
        },
        "handler.batchResult": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "error": {
                    "description": "populated only on failure",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "result": {
                    "description": "\"success\" | \"failure\"",
                    "type": "string"
                }
            }
        },
        "handler.batchSummary": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "integer"
                },
                "success": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "handler.conflictResponse": {
            "type": "object",
            "properties": {
                "currentChecksum": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.messageJSON": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.serviceJSON": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "string"
                },
                "fragmentPath": {
                    "type": "string"
                },
                "load": {
                    "type": "string"
                },
                "locked": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "sub": {
                    "type": "string"
                },
                "unitFileState": {
                    "type": "string"
                }
            }
        },
        "handler.sessionJSON": {
            "type": "object",
            "properties": {
                "authenticated": {
                    "type": "boolean"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handler.tokenListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/token.TokenResponse"
                    }
                }
            }
        },
        "notify.ChannelType": {
            "type": "string",
            "enum": [
                "slack",
                "discord",
                "telegram",
                "custom"
            ],
            "x-enum-varnames": [
                "ChannelTypeSlack",
                "ChannelTypeDiscord",
                "ChannelTypeTelegram",
                "ChannelTypeCustom"
            ]
        },
        "notify.HistoryEntry": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "string"
                },
                "channel_name": {
                    "type": "string"
                },
                "channel_type": {
                    "type": "string"
                },
                "duration_ms": {
                    "description": "含 retry 的總耗時",
                    "type": "integer"
                },
                "error": {
                    "description": "失敗原因",
                    "type": "string"
                },
                "event": {
                    "description": "started/stopped/failed/restarted/test",
                    "type": "string"
                },
                "service": {
                    "description": "nginx.service",
                    "type": "string"
                },
                "status": {
                    "description": "success/failure",
                    "type": "string"
                },
                "timestamp": {
                    "description": "RFC3339 UTC",
                    "type": "string"
                }
            }
        },
        "notify.HistoryResult": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/notify.HistoryEntry"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "systemd.ValidateError": {
            "type": "object",
            "properties": {
                "line": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "systemd.ValidateResult": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/systemd.ValidateError"
                    }
                },
                "message": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "token.CreateTokenInput": {
            "type": "object",
            "properties": {
                "custom_expiry": {
                    "description": "僅 expires_in_days=0 時使用",
                    "type": "string"
                },
                "expires_in_days": {
                    "description": "-1 = 永不過期, 1-365 = N 天, 0 = 自訂日期",
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "scope": {
                    "$ref": "#/definitions/token.Scope"
                }
            }
        },
        "token.CreateTokenResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "scope": {
                    "$ref": "#/definitions/token.Scope"
                },
                "token": {
                    "description": "RAW value — 僅此一次",
                    "type": "string"
                }
            }
        },
        "token.RevokeResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "description": "\"revoked\" | \"already_revoked\"",
                    "type": "string"
                }
            }
        },
        "token.Scope": {
            "type": "string",
            "enum": [
                "read",
                "full"
            ],
            "x-enum-comments": {
                "ScopeFull": "完整操作：所有 HTTP method",
                "ScopeRead": "唯讀：僅 GET / HEAD / OPTIONS"
            },
            "x-enum-descriptions": [
                "唯讀：僅 GET / HEAD / OPTIONS",
                "完整操作：所有 HTTP method"
            ],
            "x-enum-varnames": [
                "ScopeRead",
                "ScopeFull"
            ]
        },
        "token.Status": {
            "type": "string",
            "enum": [
                "active",
                "expiring_soon",
                "expired",
                "revoked"
            ],
            "x-enum-varnames": [
                "StatusActive",
                "StatusExpiringSoon",
                "StatusExpired",
                "StatusRevoked"
            ]
        },
        "token.TokenResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_used_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "prefix": {
                    "description": "前 4 字元 + \"****\" + 後 4 字元",
                    "type": "string"
                },
                "scope": {
                    "$ref": "#/definitions/token.Scope"
                },
                "status": {
                    "$ref": "#/definitions/token.Status"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Linux Service Manager API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
